# Generated by Django 5.1 on 2024-10-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadsalud',
            name='codEntidad',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
